### ISSUE TITLE
How to Parse JSON object and map it to POJO 

### ISSUE THREAD

**Issue by austindsouza** [fortyrunner/ignite-test#1]
Hi,

I was going through your source code and I saw that you are reading the CSV file and mapping it to objects, My use case is to parse the JSON data and map it to POJO class...

How to do this... 
Can you please help me on this.

Thanks

**Comment by fortyrunner** [comment]
Normally, I would use the Apache Camel component called Bindy to map CSV to Java Objects.

For JSON, you could use http://camel.apache.org/json.html and pick one of the three libraries to do the unmarshalling for you.

I have used XStream in the past for marshalling purposes and its very easy to setup and use. I have also used Jackson and that was equally as easy. I haven't used GSON - but Google projects are (as you would expect)  of a high quality.
